services:
    odiseo_rbac.event_listener.admin.menu_builder:
        class: Odiseo\SyliusRbacPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
