services:
    odiseo_rbac.permission.route_resolver:
        class: Odiseo\SyliusRbacPlugin\Permission\Discovery\RoutePermissionResolver

    odiseo_rbac.permission.discoverer.resource_route:
        class: Odiseo\SyliusRbacPlugin\Permission\Discovery\ResourceRoutePermissionDiscoverer
        arguments:
            - '@router'
            - '@odiseo_rbac.permission.route_resolver'
            - '%odiseo_rbac.handled_routes%'
            - '%sylius_admin.path_name%'

    odiseo_rbac.permission.discoverer.declared:
        class: Odiseo\SyliusRbacPlugin\Permission\Discovery\DeclaredPermissionDiscoverer
        arguments:
            - '%odiseo_rbac.declared_permissions%'

    odiseo_rbac.permission.discoverer:
        class: Odiseo\SyliusRbacPlugin\Permission\Discovery\ChainPermissionDiscoverer
        arguments:
            -
                - '@odiseo_rbac.permission.discoverer.resource_route'
                - '@odiseo_rbac.permission.discoverer.declared'

    odiseo_rbac.permission.registry_factory:
        class: Odiseo\SyliusRbacPlugin\Permission\PermissionRegistryFactory
        arguments:
            - '@odiseo_rbac.permission.discoverer'

    odiseo_rbac.permission.registry:
        class: Odiseo\SyliusRbacPlugin\Permission\PermissionRegistry
        factory: ['@odiseo_rbac.permission.registry_factory', 'createRegistry']

    Odiseo\SyliusRbacPlugin\Permission\PermissionRegistryInterface: '@odiseo_rbac.permission.registry'

    odiseo_rbac.command.debug_permissions:
        class: Odiseo\SyliusRbacPlugin\Command\DebugPermissionsCommand
        arguments:
            - '@odiseo_rbac.permission.discoverer'
        tags:
            - { name: console.command }

    odiseo_rbac.permission.route_map:
        class: Odiseo\SyliusRbacPlugin\Permission\RoutePermissionMap
        arguments:
            - '@router'
            - '@odiseo_rbac.permission.route_resolver'
            - '%odiseo_rbac.route_identifiers%'
            - '%odiseo_rbac.public_routes%'

    Odiseo\SyliusRbacPlugin\Permission\RoutePermissionMapInterface: '@odiseo_rbac.permission.route_map'
