parameters:
    root_administrator_email: ''

sylius_fixtures:
    suites:
        default_rbac_fixtures:
            fixtures:
                administration_role:
                    options:
                        name: 'No sections access'

            listeners:
                logger: ~

sylius_resource:
    resources:
        sylius_rbac.administration_role:
            classes:
                model: Odiseo\SyliusRbacPlugin\Entity\AdministrationRole
                interface: Odiseo\SyliusRbacPlugin\Entity\AdministrationRoleInterface

sylius_grid:
    grids:
        sylius_rbac_administration_role:
            driver:
                name: doctrine/orm
                options:
                    class: Odiseo\SyliusRbacPlugin\Entity\AdministrationRole
            fields:
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                        options:
                            link:
                                route: sylius_rbac_admin_administration_role_create_view
                item:
                    update:
                        type: update
                        options:
                            link:
                                route: sylius_rbac_admin_administration_role_update_view
                                parameters:
                                    id: resource.id
        sylius_admin_admin_user:
            fields:
                administration_role:
                    type: twig
                    label: sylius_rbac.ui.administration_role
                    sortable: true
                    options:
                        template: '@OdiseoSyliusRbacPlugin/AdministrationRole/Grid/Field/administrationRole.html.twig'

odiseo_sylius_rbac:
    sylius_sections:
        catalog_management:
            - sylius_admin_inventory
            - sylius_admin_product
            - sylius_admin_product_association_type
            - sylius_admin_product_attribute
            - sylius_admin_product_option
            - sylius_admin_product_variant
            - sylius_admin_taxon
        configuration:
            - sylius_admin_admin_user
            - sylius_admin_channel
            - sylius_admin_country
            - sylius_admin_currency
            - sylius_admin_exchange_rate
            - sylius_admin_locale
            - sylius_admin_payment_method
            - sylius_admin_shipping_category
            - sylius_admin_shipping_method
            - sylius_admin_tax_category
            - sylius_admin_tax_rate
            - sylius_admin_zone
        customers_management:
            - sylius_admin_customer
            - sylius_admin_customer_group
            - sylius_admin_shop_user
        marketing_management:
            - sylius_admin_product_review
            - sylius_admin_promotion
            - sylius_admin_catalog_promotion
        sales_management:
            - sylius_admin_order
            - sylius_admin_payment
            - sylius_admin_shipment
    custom_sections:
        rbac:
            - sylius_rbac
