Odiseo\SyliusRbacPlugin\Entity\AdministrationRole:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [code]
            message: 'odiseo_rbac.administration_role.code.unique'
            groups: ['odiseo']
    properties:
        code:
            - NotBlank:
                message: 'odiseo_rbac.administration_role.code.not_blank'
                groups: ['odiseo']
            - Length:
                min: 2
                max: 255
                minMessage: 'odiseo_rbac.administration_role.code.min_length'
                maxMessage: 'odiseo_rbac.administration_role.code.max_length'
                groups: ['odiseo']
            - Regex:
                pattern: '/^[a-zA-Z0-9_-]+$/'
                message: 'odiseo_rbac.administration_role.code.regex'
                groups: ['odiseo']
